[book]
authors = ["Sebastian Beyvers", "Jannis Hochmuth", "Lukas Brehm", "Frank Förster", "Maria Hansen"]
language = "en"
multilingual = false
src = "."
title = "Presentations by the Aruna project"
build-dir = "book"

[output.html]
smart-punctuation = true
git-repository-url = "https://github.com/ArunaStorage/presentations/tree/main"
edit-url-template = "https://github.com/ArunaStorage/presentations/edit/main/{path}"


[preprocessor.alerts]