[book]
authors = ["Sebastian Beyvers", "Jannis Hochmuth", "Lukas Brehm", "Frank Förster", "Maria Hansen"]
language = "en"
multilingual = false
src = "src"
title = "Presentations by the Aruna project"


[preprocessor.alerts]