[book]
authors = ["Sebastian Beyvers", "Jannis Hochmuth", "Lukas Brehm", "Frank Förster", "Maria Hansen"]
language = "en"
multilingual = false
src = "."
title = "Presentations by the Aruna project"
build-dir = "book"

[preprocessor.alerts]